/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableauDeBordIndexRouteImport } from './routes/tableau-de-bord/index'
import { Route as OrganismesIndexRouteImport } from './routes/organismes/index'
import { Route as OffresIndexRouteImport } from './routes/offres/index'
import { Route as EspaceOrganismeIndexRouteImport } from './routes/espace-organisme/index'
import { Route as PostulerSlugRouteImport } from './routes/postuler/$slug'
import { Route as OrganismesSlugRouteImport } from './routes/organismes/$slug'
import { Route as OffresSlugRouteImport } from './routes/offres/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordIndexRoute = TableauDeBordIndexRouteImport.update({
  id: '/tableau-de-bord/',
  path: '/tableau-de-bord/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganismesIndexRoute = OrganismesIndexRouteImport.update({
  id: '/organismes/',
  path: '/organismes/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresIndexRoute = OffresIndexRouteImport.update({
  id: '/offres/',
  path: '/offres/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceOrganismeIndexRoute = EspaceOrganismeIndexRouteImport.update({
  id: '/espace-organisme/',
  path: '/espace-organisme/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostulerSlugRoute = PostulerSlugRouteImport.update({
  id: '/postuler/$slug',
  path: '/postuler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganismesSlugRoute = OrganismesSlugRouteImport.update({
  id: '/organismes/$slug',
  path: '/organismes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresSlugRoute = OffresSlugRouteImport.update({
  id: '/offres/$slug',
  path: '/offres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/offres/$slug': typeof OffresSlugRoute
  '/organismes/$slug': typeof OrganismesSlugRoute
  '/postuler/$slug': typeof PostulerSlugRoute
  '/espace-organisme/': typeof EspaceOrganismeIndexRoute
  '/offres/': typeof OffresIndexRoute
  '/organismes/': typeof OrganismesIndexRoute
  '/tableau-de-bord/': typeof TableauDeBordIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/offres/$slug': typeof OffresSlugRoute
  '/organismes/$slug': typeof OrganismesSlugRoute
  '/postuler/$slug': typeof PostulerSlugRoute
  '/espace-organisme': typeof EspaceOrganismeIndexRoute
  '/offres': typeof OffresIndexRoute
  '/organismes': typeof OrganismesIndexRoute
  '/tableau-de-bord': typeof TableauDeBordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/offres/$slug': typeof OffresSlugRoute
  '/organismes/$slug': typeof OrganismesSlugRoute
  '/postuler/$slug': typeof PostulerSlugRoute
  '/espace-organisme/': typeof EspaceOrganismeIndexRoute
  '/offres/': typeof OffresIndexRoute
  '/organismes/': typeof OrganismesIndexRoute
  '/tableau-de-bord/': typeof TableauDeBordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/offres/$slug'
    | '/organismes/$slug'
    | '/postuler/$slug'
    | '/espace-organisme/'
    | '/offres/'
    | '/organismes/'
    | '/tableau-de-bord/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/offres/$slug'
    | '/organismes/$slug'
    | '/postuler/$slug'
    | '/espace-organisme'
    | '/offres'
    | '/organismes'
    | '/tableau-de-bord'
  id:
    | '__root__'
    | '/'
    | '/offres/$slug'
    | '/organismes/$slug'
    | '/postuler/$slug'
    | '/espace-organisme/'
    | '/offres/'
    | '/organismes/'
    | '/tableau-de-bord/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OffresSlugRoute: typeof OffresSlugRoute
  OrganismesSlugRoute: typeof OrganismesSlugRoute
  PostulerSlugRoute: typeof PostulerSlugRoute
  EspaceOrganismeIndexRoute: typeof EspaceOrganismeIndexRoute
  OffresIndexRoute: typeof OffresIndexRoute
  OrganismesIndexRoute: typeof OrganismesIndexRoute
  TableauDeBordIndexRoute: typeof TableauDeBordIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord/': {
      id: '/tableau-de-bord/'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord/'
      preLoaderRoute: typeof TableauDeBordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organismes/': {
      id: '/organismes/'
      path: '/organismes'
      fullPath: '/organismes/'
      preLoaderRoute: typeof OrganismesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres/': {
      id: '/offres/'
      path: '/offres'
      fullPath: '/offres/'
      preLoaderRoute: typeof OffresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-organisme/': {
      id: '/espace-organisme/'
      path: '/espace-organisme'
      fullPath: '/espace-organisme/'
      preLoaderRoute: typeof EspaceOrganismeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postuler/$slug': {
      id: '/postuler/$slug'
      path: '/postuler/$slug'
      fullPath: '/postuler/$slug'
      preLoaderRoute: typeof PostulerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organismes/$slug': {
      id: '/organismes/$slug'
      path: '/organismes/$slug'
      fullPath: '/organismes/$slug'
      preLoaderRoute: typeof OrganismesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres/$slug': {
      id: '/offres/$slug'
      path: '/offres/$slug'
      fullPath: '/offres/$slug'
      preLoaderRoute: typeof OffresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OffresSlugRoute: OffresSlugRoute,
  OrganismesSlugRoute: OrganismesSlugRoute,
  PostulerSlugRoute: PostulerSlugRoute,
  EspaceOrganismeIndexRoute: EspaceOrganismeIndexRoute,
  OffresIndexRoute: OffresIndexRoute,
  OrganismesIndexRoute: OrganismesIndexRoute,
  TableauDeBordIndexRoute: TableauDeBordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
